<script setup lang="ts">
import type { Exam } from '@/interfaces/Exam';
import { summarizeExams } from '@/utils/ai_utils';
import { onMounted, ref } from 'vue';
import '@material/web/progress/circular-progress.js';
import type { User } from '@/interfaces/User';

interface ComponentProps {
    exams: Exam[];
    user: User;
}

const props = defineProps<ComponentProps>();

const emit = defineEmits(['error']);

const summary = ref<string>('');
const message = ref<string>('');
const isComplete = ref<boolean>(false);
const hasError = ref<boolean>(false);
const modelDownloadProgress = ref<number | null>(null);

function onChunk(generatedSummary: string) {
    summary.value = generatedSummary;
}

function onDownload(progress: number) {
    modelDownloadProgress.value = progress;
}

function onEvent(receivedMessage: string) {
    message.value = receivedMessage;
}

function onComplete() {
    isComplete.value = true;
}

onMounted(async () => {
    try {
        await summarizeExams(props.exams, props.user, onChunk, onDownload, onEvent, onComplete);
    } catch (error) {
        hasError.value = true;
        if (error instanceof Error) message.value = error.message;
        emit('error', error);
    }
});
</script>

<template>
    <div class="summary-container">
        <h1 class="summary-header">AI Summary</h1>
        <div class="loading" v-if="modelDownloadProgress !== null && modelDownloadProgress < 1">
            <md-circular-progress :value="modelDownloadProgress"></md-circular-progress>
            <p class="loading-message">Downloading Gemini Nano ({{ Math.round(modelDownloadProgress * 100) }}% complete)</p>
        </div>
        <div v-else-if="!summary && !hasError && modelDownloadProgress === null" class="loading">
            <md-circular-progress indeterminate four-color></md-circular-progress>
            <p class="loading-message">{{ message }}</p>
        </div>
        <div v-if="summary" class="summary-content">
            <p>{{ summary }}</p>
            <p v-if="isComplete" class="disclaimer">Generated by Gemini Nano. Gemini Nano is AI and can make mistakes.</p>
        </div>
        <p v-if="hasError" class="error-message">{{ message }}</p>
    </div>
</template>

<style scoped>
.summary-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    padding: 20px;
}

.summary-header {
    color: var(--md-sys-color-primary);
}

.loading {
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.loading-message {
    color: var(--md-sys-color-primary);
}

.disclaimer {
    color: var(--md-sys-color-on-surface-variant);
    font-size: 0.7rem;
}

.error-message {
    color: var(--md-sys-color-error);
}

.summary-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
</style>